### ISSUE TITLE
Source Code is HTML Escaped

### ISSUE THREAD

**Issue by southdesign** [jonschlinkert/remarkable#147]
Hey there,

If i write source code like:

```swift
func test() -> Int?{
  a > b
}
```

the `->` and `a > b` is converted to `-&gt;` and `a &gt; b`.

I think this should not be the case in source code.

**Comment by vyp** [comment]
I might be wrong, but I think HTML requires that angle brackets always be escaped (when not used to define tags of course), even in `pre` tags.

If I'm right, then this would be out of scope here. Also, https://html5.validator.nu/ says your example is invalid html.

**Comment by southdesign** [comment]
You're right. From  a first glance, it appears that it has to do with highlightjs`s autoHighlight feature.

I copied it from the remarkable Readme. I will have time to look into it later.

**Comment by vyp** [comment]
> From a first glance, it appears that it has to do with highlightjs`s autoHighlight feature.

Possibly. But [this demo](https://jonschlinkert.github.io/remarkable/demo/#md64=eyJzb3VyY2UiOiJgYGBcbmZ1bmMgdGVzdCgpIC0+IEludD97XG4gIGEgPiBiXG59XG5gYGAiLCJkZWZhdWx0cyI6eyJodG1sIjpmYWxzZSwieGh0bWxPdXQiOmZhbHNlLCJicmVha3MiOmZhbHNlLCJsYW5nUHJlZml4IjoibGFuZ3VhZ2UtIiwibGlua2lmeSI6ZmFsc2UsInR5cG9ncmFwaGVyIjpmYWxzZSwiX2hpZ2hsaWdodCI6ZmFsc2UsIl9zdHJpY3QiOmZhbHNlLCJfdmlldyI6InNyYyJ9fQ==) (with the highlight box unticked) also escapes the angle brackets (click on the source tab).

**Comment by southdesign** [comment]
Okay, it has nothing to do with highlight js. However I tested both the latest Chrome and Safari on Mac but can't get them to display an entity in the parsed form.

For both if I do:

`(new Remarkable()).render("This is > than that")` // This is &gt; than that
`(new Remarkable()).render("This is &gt; than that")` // This is &gt; than that

is outputted. But if I append the result to a `p` or write it directly to the `p` using dev tools it is not converted to the actual value but displayed as entity in plaintext. Both with `<meta charset="UTF-8">` and without.

Do you have any Idea what this could be?

**Comment by southdesign** [comment]
Could it be that the current version has a problem with entity decoding? To me it looks like this - or does remarkable not do automatic entity encoding at all?

**Comment by vyp** [comment]
> But if I append the result to a p or write it directly to the p using dev tools it is not converted to the actual value but displayed as entity in plaintext.

Hmmm, this doesn't make sense. Just so I'm clear, where exactly are you viewing this, in the chrome dev tools itself, or on the web page (on which you used dev tools to manipulate)?

> or does remarkable not do automatic entity encoding at all?

I don't know, or don't remember (haven't looked at remarkable for a while, I'm just a random, not a collaborator or anything).

I myself am on firefox and the entities are rendered okay for me.

**Comment by southdesign** [comment]
Okay, I have the solution.

The problem was (as expected) on my side. I used `document.body.innerHTML` to feed markdown into remarkable and just read that this automatically converts those special characters to &amp; etc. (https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML).

The fix was pretty easy and has nothing to do with remarkable which was absolutely fine:
Replace `document.body.innerHTML` with `document.body.textContent`.

I'm sorry for causing you trouble!

**Comment by vyp** [comment]
@southdesign Thanks for the follow up here!

>  I used document.body.innerHTML to feed markdown into remarkable and just read that this automatically converts those special characters to `&amp;`

This should be expected I believe. You obviously already know this, but just to re-clarify, the whole premise of a *markup* language/syntax (like HTML) is just that, there's some sort syntax that's special and used for markup. Hence when you want to use *actual* `<` or `>` in your document, they have to be escaped.

Now when you're typing markdown though, this shouldn't really make any difference to you, i.e. the persion writing the original markdown content in the first place. You shouldn't need to type `&gt;` in your markdown code block instead of just `>`, because whatever you're using to convert the markdown to html (in this case remarkable), should be doing that for you. The result is that you see the correct thing in the actual html document in the browser.

I know how patronising all that seems, but that's not my intention! I just want to re-explain a bit so that we're on the same wavelength here.

But yes, now I understand why you asked about this. Say you would want to parse the contents of all the code blocks (perhaps for syntax highlighting or whatever), you probably want the verbatim *text* content of the block, not the html proper. So yes, you're correct `document.body.textContent` would be what you want. (Or similarly just the `.text()` method if using jquery or something similar.)

> I'm sorry for causing you trouble!

Not at all! Again, not an official collaborator or anything here anyway, so just my own agency really.
