### ISSUE TITLE
plugins for numbered sections

### ISSUE THREAD

**Issue by itajaja** [jonschlinkert/remarkable#153]
This issue is more for asking help on how to create a plugin. I know that there is already an issue asking for a tutorial (#48) but right now I wouldn't know where to start.

Let's say I have this input:

````md
# foo

## bar

# foobar
````

I would like to add numbered sections automatically, so that the output will be equivalent to the output of the following input

````md
# 1 foo

## 1.1 bar

# 2 foobar
````

What is the best way to do that as a plugin? How would you do that?

Another way would be to generate the ast with the `parse()` method and then add the counters automatically. but how do I render a parsed ast with the public APIs? the render() method only works with strings.

**Comment by jonschlinkert** [comment]
Cool, this is something I started working on at one point. Not for remarkable, I think it was marked at the time. 

> output will be equivalent to the output of the following input

meaning that you would expect to render HTML, correct? might be stating the obvious, but I personally also use remarkable to render markdown so I want to make sure.

Here are a couple of plugins for reference:

- https://github.com/jonschlinkert/pretty-remarkable: this one uses custom renderer rules to generate markdown instead of HTML. If you look at how I'm customizing the rules, you would do the same, but you'd really only need to modify the headings.
- https://github.com/jonschlinkert/markdown-toc: this is a remarkable plugin, but it's not exposed as one (it was a refactor of a non-remarkable project, and I wanted to keep the API consistent). Here, I'm only using the headings to generate a table of contents. 

For generating the numbers, are a couple of other libs that might be useful:

- [romanize](https://github.com/jonschlinkert/romanize)
- [deromanize](https://github.com/jonschlinkert/deromanize)

**Comment by itajaja** [comment]
> meaning that you would expect to render HTML, correct?

Correct

Thanks! markdown-toc sounds the best way to start, I can take inspiration from how that plugin is made. Thanks also for the romanize/deromanize libraries.

**Comment by vyp** [comment]
This is probably not what you want, but if you want this just for a stylistic option with HTML, just fyi you can sort of already do this with CSS. Example: http://jsfiddle.net/Labmspas/. Note that it uses the CSS `content` property, so it afaik it can't be interacted with (in the browser). (Aka it can't be copy pasted.)

**Comment by itajaja** [comment]
Wow I didn't know about that css property! This would be ok if it wasn't that if you generate TOC with it,  the toc will not have the numbering...

**Comment by vyp** [comment]
Yes true. For my personal and experimental markdown setup, I use the above method for the headings, but I somehow also seem to have numbering in my toc as well... Let me figure out again how I did that (or if it was automatically generated with something else instead)...

**Comment by jonschlinkert** [comment]
great point! thanks @vyp

**Comment by vyp** [comment]
Ah I see. I actually use pandoc markdown and automatically generate the toc for the document (with the `--toc` switch). So you're still going to have to use some toc generation library I believe. However the toc that pandoc generates is not numbered, nor do I recall that pandoc offers an option to number it, so I use a similar css stylistic setup for that: http://jsfiddle.net/qus11L3a/.

Note I just copy pasted that automatically generated toc html (from a rough note), hence the cruft.

**Comment by vyp** [comment]
Basically, it depends on the toc generation library, but if the toc html it produces is some sort of list (`ul` or `ol`), then the above may help, if you're interested.

**Comment by itajaja** [comment]
you are right, I can apply the same style to the TOC. let me try that. This would be a much cleaner solution than actually messing with the markdown ast. :+1:
