### ISSUE TITLE
Quotes rendering not right

### ISSUE THREAD

**Issue by AndreyNikitin** [jonschlinkert/remarkable#166]
when rendering quotes and there is no space before quotes or after the quotes symbol is not ```”```, but ```"```
![image](https://cloud.githubusercontent.com/assets/4637442/9631507/0f80693a-518a-11e5-821e-4a61a4faab50.png)

check done on http://jonschlinkert.github.io/remarkable/demo/

**Comment by jonschlinkert** [comment]
if you fix the typos in your text and add a space in `a"text"` and `"text"a` it works as expected

**Comment by AndreyNikitin** [comment]
@jonschlinkert, what should I do with commas in sentence? some text "some text". This kind of text is not rendering right.

**Comment by aleemb** [comment]
@AndreyNikitin not sure why @jonschlinkert closed this issue, it is actually a bug.

I wouldn't expect any fixes within this project since the original people who wrote this have abandoned this relocated to https://github.com/markdown-it/markdown-it/ which indeed does fix this issue and dozens more.

You can verify that it works in Markdown-it via https://markdown-it.github.io/
