### ISSUE TITLE
Possible to add bbtags?

### ISSUE THREAD

**Issue by iliakan** [jonschlinkert/remarkable#179]
Can I add custom bbtags to remarkable?

Something like `[demo]` or `[codetabs src="..."]` or `[compare]...[/compare]`.

**Comment by DiscoNova** [comment]
The "easy answer" is a resounding "yes"... however, this does not come without bells attached.

I believe it is easiest to do that with "plugin" (last time I checked - which, granted, was a few months ago - implementing plugins was a bit out of the scope of the documentation; thus - you need to use the source, Luke;)

I *think* (and could be entirely mistaken) that accomplishing this, you would need to override stuff in html_re in order to support BB-tags' syntax (i.e. square brackets instead of larger-than / smaller-than -signs around tags) and you would need to add handlers for the specific tags you intend to support.

Of course, if you could live with "simply" supporting an extended SGML-syntax, you could entirely skip the overrides in html_re (because instead of `[codetabs src="..."]` you would really be hunting for `<codetabs src="...">` etc.)

**Comment by iliakan** [comment]
Switched to https://github.com/markdown-it/markdown-it.

Thanks @puzrin for the help in accomplishing this thing and many others!
