### ISSUE TITLE
Relative path link not working

### ISSUE THREAD

**Issue by hipstersmoothie** [jonschlinkert/remarkable#299]
I have two mark down files

```
# My Awesome Docs

* [Example](./moreDocs/example.md)
```

```
# lots of nice things

### nice thing
```

and expect the links to get transformed into working ones but they remain the same.
```html
<h1>My Awesome Docs</h1>
<ul>
<li><a href="./moreDocs/example.md">Example</a></li>
</ul>
```

I tried turning on linkify but that did not help. Is this currently a capability of remarkable?

**Comment by doowb** [comment]
Remarkable itself does not have that capability because it only works on markdown strings and doesn't have the concept of multiple files.

You can try [assemble](https://github.com/assemble/assemble) which was made for building static websites.

Also, there have been other issues about links in this project with examples of how to customize how the links are handled. You can handle your links through a customization specific to your setup (since you didn't specify anything about how the files are built into pages it's hard to guess what's right for you).
