### ISSUE TITLE
Update Dep Argparse to 1.0.10

### ISSUE THREAD

**Issue by DarrenMack-OD** [jonschlinkert/remarkable#321]
Could you please update the dependency argparse to 1.0.10 please?

**Comment by jdalegonzalez** [comment]
@jonschlinkert Do have thoughts on when the associated PR can get merged?

**Comment by 808loud** [comment]
Even just updating the dependency to version ^1 should resolve the issue

**Comment by DarrenMack-OD** [comment]
Can someone tell me what the hold-up is?

**Comment by jonschlinkert** [comment]
This needs to be resolved on argparse. Otherwise every single minor and major version of every single downstream library will need to be patched. By patching it here, we are not fixing the problem, we are only silencing your own personal terminal. 

Just as importantly importantly, there is no security vulnerability to this library, unless you plan to attack yourself. Which means that every person complaining on this library is not interested in actually solving the problem. If you want to solve the problem, go be persistent on argparse until they patch so that it rolls up to every downstream library. The fact that newer versions of argparse are fixed doesn’t matter, a patch needs to be released on every major version of argparse where the bug existed. 

If you still want to complain here, then you don’t understand the problem.

**Comment by jdalegonzalez** [comment]
Hey Jon, I’m confused by your answer.  It’s my understanding that the security problem has been fixed by argparse.  There is a version provided by them that no longer has the vulnerability.  Are you suggesting that argparse should backport all security fixes to all versions?  Is your concern that you have to upgrade in order to get the fix?  Requiring backporting to n-versions back, no matter how old seems like a big ask to make.  I also understand that the problem is command line only.  On the other hand, not accepting the PR for upgrading argparse to the latest version means that we all have to look at the security warnings, evaluate whether or not these ones “matter” and then move on versus looking at a clean screen and knowing we’re doing all we can.  Signal attenuation is a real problem and detecting the different between “2 problems” and “3 problems” is harder than detecting the difference between “0 and 1”. 

 

I know you’ve got a lot on your plate and that you maintain this package as a service to the community.  I also know that you feel like NPM is cynically motivated to make security issues high-profile in order to compete with yum.  Still, it feels like there is a PR waiting to be approved that solves the issue in your preferred way (incorporating the argparse fix) and we would all benefit if you would approve it. 

 

But, perhaps I don’t understand the problem either.  I’m happy to be educated.

**Comment by DarrenMack-OD** [comment]
Sorry, I believe my PR fixes the issue quite nicely and as @jdalegonzalez says, argparse is patched, which is what my PR incorporates. I thought the whole point of GitHub was a communal effort, I've created the PR so you don't have to, as you are obviously busy with other things. If my PR doesn't fix the issue then please educate me, as I believed it to have solved the problem in question and eradicates the warnings.

My apologise for treading on your toes, I'll revoke my PR and you can do it yourself!

**Comment by jonschlinkert** [comment]
> Hey Jon, I’m confused. It’s my understanding that the security problem has been fixed by argparse.

**Please think about the following sentence: If it was fixed, you would not be seeing the message in the command line.** I am going to explain in detail why you are seeing the message, and how it needs to be fixed. 

Let's say you do the following:

- You create a library and release v0.1.0
- You then make some upgrades and release v1.0
- Later, you discover that there is was a bug in v0.1.0 and it affects many other libraries that depend on your package, but it has been fixed in 1.0.

**INCORRECT** 

- You tell everyone to upgrade to v1.0 to get the fix. 
- this means that every single downstream library in the ecosystem that depends on your library needs to upgrade to get a patch. AND every older version that depended on the buggy version needs to be patched. Semantic versioning was created to eliminate the need to do this. 

PLEASE re-read this section until it sinks in completely. If you don't understand some part of it, I'd be happy to explain.

**CORRECT**

- Retroactively create and publish a patch version, `v0.1.1`, to fix the security vulnerability. Yes, this means, even though the library has "solved the problem" in newer major versions, _they have NOT released a patch on the versions where the patch is needed_. 
- This way every single library gets the path. 

PLEASE stop asking me to patch this. Do the correct thing and go complain on argparse until they push up a patch. 

To you, this might be one annoying issue that needs to be fixed. To me, it ripples across the ~500 active libraries I maintain and it would mean a great deal to me if you helped fix the root of the problem instead of hacking at the leaves.

**Comment by jonschlinkert** [comment]
> I thought the whole point of GitHub was a communal effort,

It sure it, and we can demonstrate that here by being as loud and clear about this issue as we can on argparse until it's fixed _in older versions_. 

I have had to retroactively patch older versions of libraries many, many times. It's irresponsible for the argparse maintainers to not do this. 

_Since it isn't possible for argparse to cause a vulnerability here_, we have no good argument not to wait until the problem is fixed at the root. I care about the ecosystem, and I don't like the idea of patching over something that might be a real security concern on other libraries that depend on argparse.

**Comment by DarrenMack-OD** [comment]
From the mouth of the argParse dev himself;
> "Sorry, no plans to support ancient versions. All versions have stable/compatible API. If someone don't like to change deps - that should not become my problem."

**Comment by DarrenMack-OD** [comment]
Stalemate I guess...

**Comment by jonschlinkert** [comment]
I would take a PR to replace argparse with miminist.

**Comment by jdalegonzalez** [comment]
#327 
OK.  I've put up a PR that uses minimist.  I didn't attempt to re-implement all the features in argparse that are not present in minimist and I didn't make the function signature identical to the argparse signature (in part because I wanted it to be obvious that there was another parser being used with fewer features) BUT it does do the things necessary for bin/remarkable.js and support/specsplit.js - the only two places I saw argparse in use.

**Comment by jonschlinkert** [comment]
Fantastic! Thank you!

**Comment by jdalegonzalez** [comment]
You're welcome. Thanks for remarkable. It's an important part of our
project.

**Comment by DiscoNova** [comment]
Without checking how/for what argparse is/was being used (because it is so much easier to ask than check, sorry:) ... this switch over to minimist doesn't change remarkable's public API in any way? Just... the way things work "under the hood" so to say?

**Comment by jdalegonzalez** [comment]
It wasn't intended to change anything.  I tried to mimic even the help text and return codes that argparse was sending back on failure.  I didn't try every possible failure condition though so I can't guarantee that something isn't "different".  However, if it is, it's in a failure condition, not a success condition.

**Comment by DiscoNova** [comment]
Personally, I'd consider giving #327 a "thumbs up" ... since minimist does have less dependencies than argparse (granted; 0 vs. 1 isn't that much of a deal - but it is "less things to worry about downstream":)

And seeing how it doesn't affect the public API, it shouldn't be a breaking change.

**Comment by uiteoi** [comment]
I understand that the best fix is a patch from argparse of every major version, and that npm is overzealous in reporting vulnerabilities to dependent libraries without evaluating the real impact of dependencies vulnerabilities on dependent libraries (which is arguably very hard to do).

Yet the current argparse version referenced by remarkable is **0.1.15**, which is [an initial development phase version according to semver](https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase).

Consequently it is unlikely that argparse would ever fix all its development releases, because there were no major releases before 1.0 which is the first major release, unless we consider all development releases major, which is not specified by semver. The whole point of development releases is to not have to provide support, including support to security vulnerabilities. I would not be confortable asking anyone to patch a development release after they have a non-development release.

Now that argparse has a proper major non-development release, shouldn't it be used instead, regardless of any other issue?

And yes, we do need to silence a lot of terminals in a lot of dependent libraries because this library is awesome.

So please allow the appropriate pull-request to merge. Thank you.

**Comment by DarrenMack-OD** [comment]
I actually don't understand the problem anymore... I have spoken to the dev of argParse and he is not in anyway going to patch every version of his module, if this is the approach we want to adopt, let's just do away with versioning altogether...

I have provided a patched version of this dependency, @jdalegonzalez has provided a complete replacement for this dependency, and we're still here debating it...

**Comment by jonschlinkert** [comment]
closing in favor of https://github.com/jonschlinkert/remarkable/pull/327.
