### ISSUE TITLE
Looking for collaborators

### ISSUE THREAD

**Issue by jonschlinkert** [jonschlinkert/remarkable#324]
I plan on making some changes to this library in the near future. In particular, I'll be making the plugin system easier to use and more powerful.  Until then, I need to finish up some other projects, and I'd love some help getting this library up to date. 

If you'd like to help maintain this project, and you are familiar with the code base and/or are willing to get familiar it, please let me know and I'll add you as a collaborator. Thanks!

**Comment by uiteoi** [comment]
@jonschlinkert, I would be happy to help you maintain this project. Please add me as a collaborator.

**Comment by rwky** [comment]
@jonschlinkert I'd be happy to help maintain this project. So would @idurotola and @jonnyka

We use this in production so have interest in keeping it maintained.

**Comment by jonschlinkert** [comment]
@rwky great! Many of the issues that I need help with require experience with parsers/compilers, is that something you are familiar with?

**Comment by rwky** [comment]
Nope none of us do, but we're willing to learn! We do have pleny of experience with JS/node though. The reason I saw this issue was because I ran `npm audit` and remarkable popped up as having a dependency with an issue.

We'd be happy to get the master branch cleaned up a bit so tests work, travis is up to date and npm audit doesn't complain anymore.
